### ISSUE TITLE
Health Check endpoint

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/website#126]
Hey @Heptagram-Bot-Project/website-team , can we add a Health Check endpoint `/health` to the website, returning a simple `200` status?

[https://microservices.io/patterns/observability/health-check-api.html](https://microservices.io/patterns/observability/health-check-api.html
)[https://www.ibm.com/garage/method/practices/manage/health-check-apis/](https://www.ibm.com/garage/method/practices/manage/health-check-apis/)

**Comment by sancodes** [comment]
If this is open, I am willing to help.

**Comment by j-dogcoder** [comment]
Sure!

**Comment by sancodes** [comment]
@j-dogcoder can you help me in understanding, what i really need to do?

**Comment by j-dogcoder** [comment]
Sure! For starters, I would read the 2 articles above

**Comment by sancodes** [comment]
@j-dogcoder 
Done reading those articles. 


Since I don't see any backend, 
I'm assuming my task will just to create a `/health` endpoint. 

I was thinking of doing something like this: 
`App.js`

- Add a route path to `/health-check` and link it to a Health Page, looking at the style, I see all the route path are linked to some sort of pages. 

`Pages` directory, 
- create a new file `HealthCheck.js`, which is linked to `/health-check` path. 
- since, I dont see much happening with the website, I was just going to return a status of 200.

**Comment by j-dogcoder** [comment]
That sounds good!

**Comment by sancodes** [comment]
@j-dogcoder added changes, can you help me review.

**Comment by j-dogcoder** [comment]
I put in a review @sancodes! Sorry for the wait.

**Comment by sancodes** [comment]
@j-dogcoder I have pushed in new changes, the website is now loading fine in the localhost. 
Can you take a look at it. Thank you.

**Comment by j-dogcoder** [comment]
Looking now!

**Comment by j-dogcoder** [comment]
Closed by #127
